name: DogeWorlds
author: DogeDev
version: 0.0.3
api: 4.0.0
description: "A utility-first tool for worlds management"
load: STARTUP
main: DogeDev\DogeWorlds\DogeWorlds
website: "https://github.com/doge-pm/DogeWorlds/"

permissions:
  dogeworlds.command:
    default: op
  dogeworlds.subcommmand.create:
    default: op
  dogeworlds.subcommmand.delete:
    default: op
  dogeworlds.subcommmand.list:
    default: op
  dogeworlds.subcommmand.load:
    default: op
  dogeworlds.subcommmand.rename:
    default: op
  dogeworlds.subcommmand.teleport:
    default: op
  dogeworlds.subcommmand.unload:
    default: op
